### ISSUE TITLE
有数据库的ER图吗

### ISSUE THREAD

**Issue by SwagyChill** [J1ong/FilmSys#1]
数据库大作业想参考一下...

**Comment by J1ong** [comment]
没有画ER图哦，但有数据库设计，你看用得上吗？

**Comment by SwagyChill** [comment]
嗯嗯 谢谢啦

**Comment by SwagyChill** [comment]
> 没有画ER图哦，但有数据库设计，你看用得上吗？
能留个联系方式嘛

**Comment by J1ong** [comment]
[db-design.docx](https://github.com/J1ong/FilmSys/files/3903372/db-design.docx)
数据库设计文件

**Comment by SwagyChill** [comment]
运行之后 只有一个电影和影院 是我配置的不对吗...

**Comment by J1ong** [comment]
应该是电影过了上映的时间（以当前时间为基准），在后台管理系统重新设置上映时间或者添加新电影就行了。

**Comment by SwagyChill** [comment]
嗯嗯谢谢了
可以留个联系方式嘛 可能以后还有一些问题需要问 有偿的

**Comment by J1ong** [comment]
加我qq2419782227吧
