### ISSUE TITLE
导入数据库文件如何导入？

### ISSUE THREAD

**Issue by tmo-omt** [J1ong/FilmSys#14]
我刚安装完mysql  不知道怎么导入数据库文件，没安装图形界面

**Comment by J1ong** [comment]
> 我刚安装完mysql 不知道怎么导入数据库文件，没安装图形界面
你可以试试下面这个：
常用source 命令

进入mysql数据库控制台，如

mysql -u root -p

mysql>use 数据库

然后使用source命令，后面参数为脚本文件(如这里用到的.sql)

mysql>source d:/dbname.sql(这个是文件地址)

**Comment by J1ong** [comment]
> 我刚安装完mysql 不知道怎么导入数据库文件，没安装图形界面


你可以试试下面这个：
常用source 命令

进入mysql数据库控制台，如

mysql -u root -p

mysql>use 数据库

然后使用source命令，后面参数为脚本文件(如这里用到的.sql)

mysql>source d:/dbname.sql(这个是文件地址)

**Comment by tmo-omt** [comment]
> > 我刚安装完mysql 不知道怎么导入数据库文件，没安装图形界面
> 
> 你可以试试下面这个：
> 常用source 命令
> 
> 进入mysql数据库控制台，如
> 
> mysql -u root -p
> 
> mysql>use 数据库
> 
> 然后使用source命令，后面参数为脚本文件(如这里用到的.sql)
> 
> mysql>source d:/dbname.sql(这个是文件地址)

**Comment by tmo-omt** [comment]
> > 我刚安装完mysql 不知道怎么导入数据库文件，没安装图形界面
> 
> 你可以试试下面这个：
> 常用source 命令
> 
> 进入mysql数据库控制台，如
> 
> mysql -u root -p
> 
> mysql>use 数据库
> 
> 然后使用source命令，后面参数为脚本文件(如这里用到的.sql)
> 
> mysql>source d:/dbname.sql(这个是文件地址)

感谢回复   已用查询解决
