### ISSUE TITLE
前台没有数据

### ISSUE THREAD

**Issue by xmmmmmovo** [J1ong/FilmSys#2]
在后台能够看到数据
然而在前台却显示0部...
![QHODgA.jpg](https://s2.ax1x.com/2019/12/19/QHODgA.jpg)
![QHOrjI.jpg](https://s2.ax1x.com/2019/12/19/QHOrjI.jpg)
![QHO09H.jpg](https://s2.ax1x.com/2019/12/19/QHO09H.jpg)

**Comment by J1ong** [comment]
添加电影后，还需安排影院排片哦

**Comment by xmmmmmovo** [comment]
哦哦哦 原来如此 感激!
