### ISSUE TITLE
项目导入完成一切正常就是获取不到电影列表，显示不出

### ISSUE THREAD

**Issue by coolestgaim** [J1ong/FilmSys#25]
不知道为什么，项目可以正常启动。但是主页电影页面那些数据明明有却获取不到。可以登录也可以管理后台，说明是有跟数据库交互的，会不会是请求的方式错了

**Comment by white-55** [comment]
情况跟你一样，项目能跑，后台管理系统正常，只有前端页面获取不到数据，但登录又可以，怎么解决？

**Comment by white-55** [comment]
解决了，是api接口那里做了时间的判断，获取不到过期的电影，所以把数据库里电影的上映时间全部改成将来的时间就搞定！

**Comment by openluck** [comment]
对，把数据库中的日期改下就可以了。。 改成当前

**Comment by zeng-zhang** [comment]
为啥我修改了，还是显示不出来。接口一直没有返回相关的数据
