### ISSUE TITLE
进不去后台管理界面，后台管理界面点击登录会报错是为什么？

### ISSUE THREAD

**Issue by Vous-chen** [J1ong/FilmSys#44]
[HPM] Error occurred while trying to proxy request api/admin/login from localhost:8081 to http://localhost:3000 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

**Comment by J1ong** [comment]
你排查一下3000端口的api服务器有没正常启动？

**Comment by Vous-chen** [comment]
请问..如何开启api服务器？

**Comment by J1ong** [comment]
你按照我项目里说明文档的步骤一步一步操作就可以了

**Comment by Vous-chen** [comment]
> 你按照我项目里说明文档的步骤一步一步操作就可以了

操作了...然后就报上面那个错误了...

**Comment by J1ong** [comment]
3000端口有被其它占用吗？这个...应该是3000服务器的项目没启动成功吧
