### ISSUE TITLE
手机访问此项目，电影图片无法正常显示，请问如何解决

### ISSUE THREAD

**Issue by CeWefine** [J1ong/FilmSys#45]
手机访问此项目，电影图片无法正常显示，请问如何解决

**Comment by J1ong** [comment]
可以截图看看么

**Comment by CeWefine** [comment]
![image](https://user-images.githubusercontent.com/50123873/144562857-fb7f6626-bf94-4a25-954b-0e320b21f72f.png)

**Comment by CeWefine** [comment]
能看到吗 就是上方的图片能显示，但是电影的图片，以及评论者的头像都不能显示

**Comment by J1ong** [comment]
可以截图看看么

**Comment by CeWefine** [comment]
![image](https://user-images.githubusercontent.com/50123873/144563286-436986e3-6914-449b-a674-a167e501bae0.png)

**Comment by J1ong** [comment]
发一下控制台的network

**Comment by CeWefine** [comment]
![image](https://user-images.githubusercontent.com/50123873/144563577-ebd1572e-3ff5-4fba-bb3f-51c5f9437f4f.png)

**Comment by CeWefine** [comment]
就是手机访问的时候 不能显示图片，但是用浏览器调试就可以显示图片

**Comment by J1ong** [comment]
你看一看是不是手机浏览器的广告拦截的功能打开了

**Comment by CeWefine** [comment]
![image](https://user-images.githubusercontent.com/50123873/144568128-9f281a39-b53d-4bdb-800a-4c701621e076.png)
hai'sh还是不行啊，请问您用什么手机进行访问的，是模拟器还是真机，用的哪个浏览器

**Comment by J1ong** [comment]
手机浏览器

**Comment by CeWefine** [comment]
解决了 ，全局替换localhost:3000 成 ip:3000
谢谢
