### ISSUE TITLE
请问电影院里排片信息出不来是什么问题

### ISSUE THREAD

**Issue by Parker602** [J1ong/FilmSys#56]

**Comment by J1ong** [comment]
可能时间久了，你登录一下后台系统更新一下电影数据




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "J1ong/FilmSys"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月21日(星期一) 下午5:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[J1ong/FilmSys] 请问电影院里排片信息出不来是什么问题 (Issue #56)





 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Parker602** [comment]
这速度nb

**Comment by Parker602** [comment]
等等

**Comment by Parker602** [comment]
![图片](https://user-images.githubusercontent.com/100040421/154923127-a4c2b257-da67-4376-a090-276bc928acea.png)

**Comment by Parker602** [comment]
就是这样子

**Comment by Parker602** [comment]
wco老大行了我换了个浏览器就好了之前用火狐
