### ISSUE TITLE
有api文档吗

### ISSUE THREAD

**Issue by zjp693** [J1ong/FilmSys#59]

**Comment by J1ong** [comment]
没有噢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "J1ong/FilmSys"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月3日(星期四) 上午8:46
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[J1ong/FilmSys] 有api文档吗 (Issue #59)





 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by gouyan918** [comment]
有数据库设计吗

**Comment by J1ong** [comment]
没有




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "J1ong/FilmSys"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月26日(星期二) 上午10:15
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [J1ong/FilmSys] 有api文档吗 (Issue #59)





 
有数据库设计吗
