### ISSUE TITLE
无聊的提问

### ISSUE THREAD

**Issue by zjp693** [J1ong/FilmSys#63]
无聊的提问

**Comment by J1ong** [comment]
可以的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "J1ong/FilmSys"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月8日(星期天) 中午11:36
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [J1ong/FilmSys] 可否重构项目当毕业设计 (Issue #63)





 
Reopened #63.
